requires = [ "tox>=4.25" ]
env_list = [ "fix", "helper" ]

[env.fix]
description = "run static analysis and style check"
skip_install = true
deps = [ "pre-commit-uv>=4.1.4" ]
pass_env = [ "NPM_CONFIG_REGISTRY" ]
commands = [ [ "pre-commit", "run", "--all-files", "--show-diff-on-failure" ] ]

[env.helper]
description = "helper methods"
skip_install = true
deps = [ "pygithub>=2.6.1", "rich>=14", "truststore>=0.10.1" ]
pass_env = [ "GITHUB_TOKEN", "REQUESTS_CA_BUNDLE" ]
commands = [ [ "python", "tasks/helper.py", { replace = "posargs", extend = true } ] ]

[env.dev]
description = "create dev env"
skip_install = true
deps = [
  { replace = "ref", of = [ "env.fix", "deps" ], extend = true },
  { replace = "ref", of = [ "env.helper", "deps" ], extend = true },
  "all-repos>=1.29",
  "bump-deps-index>=1.6",
]
commands = [ [ "chmod", "600", "all-repos.json" ], [ "rm", "-rf", "repos" ], [ "all-repos-clone", "-C", "all-repos.json" ] ]
allowlist_externals = [ "chmod", "rm" ]
